version: '3.8'

services:
  app:
    image: loja-projeto:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fabriciorosanet
      POSTGRES_PASSWORD: arquiteto
      POSTGRES_DB: db_ecommerce_teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: